name: Publish

on:
  push:
    branches: ['release']

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Deploy
      run: rojo upload --cookie "$ROBLOSECURITY" --asset_id 123456789
      env:
        ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}