name: Tests

on: [push, pull_request]

jobs:
  code-test:
    name: Code Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: selene --version

    - name: Run Test
      run: selene .
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Report tool versions
      run: rojo --version

    - name: Run Test
      run: rojo build --output build.rbxmx
      
